### ISSUE TITLE
缺少 VertexHelper

### ISSUE THREAD

**Issue by whisperlin** [coding2233/TextInlineSprite#1]
Assets/TextInlineSprite/Script/InlieSpriteText.cs(126,44): error CS0246: The type or namespace name `VertexHelper' could not be found. Are you missing a using directive or an assembly reference?

兄弟你代码没上传完把。

**Comment by coding2233** [comment]
看一下是不是unity版本的问题，这里最低版本是unity5.3

**Comment by coding2233** [comment]
@whisperlin 看一下是不是unity版本的问题，这里最低版本是unity5.3
