### ISSUE TITLE
请问下如何修改表情大小

### ISSUE THREAD

**Issue by EricCai1991** [coding2233/TextInlineSprite#24]
现在表情大小是依赖字体大小的，但是我想让表情变大一点，请问我要如何做好

**Comment by coding2233** [comment]
有问题可以切换到Text-v2.0-b分支，看是否满足功能上的需求

**Comment by EricCai1991** [comment]
你好，我切换到Text-v2.0-b分支修改表情大小的确有效果，但是字体和图片不是在同一水平线上,有没办法解决呢

**Comment by EricCai1991** [comment]
就是想让图片和文字是居中对齐的

**Comment by coding2233** [comment]
简单粗暴的办法 就是加一点偏移值吧

**Comment by EricCai1991** [comment]
请问下这个偏移值需要在哪个位置添加，麻烦了

**Comment by EricCai1991** [comment]
是改顶点位置么

**Comment by EricCai1991** [comment]
可以了，谢谢，测试了下没问题
