### ISSUE TITLE
5.5上面错误

### ISSUE THREAD

**Issue by chwuchang** [coding2233/TextInlineSprite#3]
在5.5里面打开直接报错 InlieText脚本167行和 461行以及327行

**Comment by Kimi2016** [comment]
Unity 5.4.3f1 (64-bit) 导入包后，直接出现的错误

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[UnityEngine.UIVertex].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
InlieText.CalcQuadTag (IList`1 verts) (at Assets/TextInlineSprite/Script/InlieText.cs:331)
InlieText.OnPopulateMesh (UnityEngine.UI.VertexHelper toFill) (at Assets/TextInlineSprite/Script/InlieText.cs:212)
UnityEngine.UI.Graphic.DoMeshGeneration () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:380)
UnityEngine.UI.Graphic.UpdateGeometry () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:374)
UnityEngine.UI.Text.UpdateGeometry () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Text.cs:381)
UnityEngine.UI.Graphic.Rebuild (CanvasUpdate update) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:334)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/CanvasUpdateRegistry.cs:149)
UnityEngine.Canvas:SendWillRenderCanvases()

**Comment by chwuchang** [comment]
InlieText 328行改下tempSprite.textpos = verts[((listTagInfor[i].index) * 4)].position;
165行for (int m = listTagInfor[i].index * 4; m < (listTagInfor[i].index  + listTagInfor[i].Length)*4; m++)

**Comment by Kimi2016** [comment]
谢谢楼主：
Unity 5.4.3f1 (64-bit)----通过上述方法，已经解决表情动画（ChattingDemo.unity、ChattingDemo_InlineSprite.unity、Text_InlineSprite.unity）可以展示出来;

TextDemo.unity 还遇到错误： 
（错误1）

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[UnityEngine.UIVertex].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
InlieText.OnPopulateMesh (UnityEngine.UI.VertexHelper toFill) (at Assets/TextInlineSprite/Script/InlieText.cs:171)
UnityEngine.UI.Graphic.DoMeshGeneration () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:384)
UnityEngine.UI.Graphic.UpdateGeometry () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:378)
UnityEngine.UI.Text.UpdateGeometry () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Text.cs:378)
UnityEngine.UI.Graphic.Rebuild (CanvasUpdate update) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:338)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/CanvasUpdateRegistry.cs:149)
UnityEngine.Canvas:SendWillRenderCanvases()


（错误2：）
NullReferenceException: Object reference not set to an instance of an object
InlieText.Update () (at Assets/TextInlineSprite/Script/InlieText.cs:465)

**Comment by Kimi2016** [comment]
谢谢楼主：
Unity 5.4.3f1 (64-bit)----通过上述方法，已经解决表情动画（ChattingDemo.unity、ChattingDemo_InlineSprite.unity、Text_InlineSprite.unity）可以展示出来;

TextDemo.unity 还遇到错误：
（错误1）

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[UnityEngine.UIVertex].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
InlieText.OnPopulateMesh (UnityEngine.UI.VertexHelper toFill) (at Assets/TextInlineSprite/Script/InlieText.cs:171)
UnityEngine.UI.Graphic.DoMeshGeneration () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:384)
UnityEngine.UI.Graphic.UpdateGeometry () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:378)
UnityEngine.UI.Text.UpdateGeometry () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Text.cs:378)
UnityEngine.UI.Graphic.Rebuild (CanvasUpdate update) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:338)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/CanvasUpdateRegistry.cs:149)
UnityEngine.Canvas:SendWillRenderCanvases()

（错误2：）
NullReferenceException: Object reference not set to an instance of an object
InlieText.Update () (at Assets/TextInlineSprite/Script/InlieText.cs:465)

-----期待楼主更新代码

**Comment by chwuchang** [comment]
在这儿加一个判断吧 我那天调试是因为前面的方法没执行完直接跳这儿了,你加一个空的判断吧！
 if (m_AnimSpriteInfor != null && !m_AnimSpriteInfor.ContainsKey(m_AnimIndex[i]))
                {
                    return;
                }
然后重启编辑器 再看看应该就对了

**Comment by chwuchang** [comment]
if (m_AnimSpriteInfor == null || !m_AnimSpriteInfor.ContainsKey(m_AnimIndex[i]))
                {
                    return;
                }
这里加个判断试试 然后重启编辑器
