### ISSUE TITLE
图片层次有问题

### ISSUE THREAD

**Issue by guopenglun** [coding2233/TextInlineSprite#34]
Unity 版本是 2018.3.8f1
Canvas模式是 Screen Space -Camera 

![image](https://user-images.githubusercontent.com/15153893/54477024-abdbed00-483e-11e9-94a0-3e3cdad6de92.png)

**Comment by coding2233** [comment]
你看看你图片的位置是不是放错了，应该是没问题的

**Comment by guopenglun** [comment]
> 你看看你图片的位置是不是放错了，应该是没问题的
谢谢您的回复，
我找到原因了
我把InlineManger脚本和SpriteGraphic 脚本放在一个GameObject下了
当前正确的做法是InlineManager的子级物体放SpriteGraphic脚本，InlineText才能正常工作。
有没有可能去掉这个限制？因为这样会让所有对象的层级更深了一层到两层。。。

**Comment by coding2233** [comment]
这个暂时没有办法，UGUI的所有组件必须遵守Canvas Renderer的渲染顺序，没有找到可自定义的接口，能动态设置渲染层级
