### ISSUE TITLE
优化请求

### ISSUE THREAD

**Issue by guopenglun** [coding2233/TextInlineSprite#39]
希望能把SpriteGraphic脚本下的CellAmount和Speed,两个值集成在SpriteAsset里面
这样在多表情的时候用一个图集即可以实现，方便管理，提升性能。
我尝试阅读代码，但无奈水平有限，无从下手。
如果您能提供下思路，我将不胜感激！谢谢。

**Comment by coding2233** [comment]
1. 在`SpriteAsset `脚本中添加`CellAmount`和`Speed`两个参数
2. 在`SpriteGraphic `脚本中的`public override Material material`里面修改
``` csharp
_defaultMater.SetFloat("_CellAmount", m_spriteAsset.CellAmount);
_defaultMater.SetFloat("_Speed", m_spriteAsset.Speed);
```

**Comment by guopenglun** [comment]
非常感谢您的帮助，这样的确可以，但是这样有个限制
所有表情的CellAmount是相同的。。
如果表情切片像这样
![1](https://user-images.githubusercontent.com/15153893/54657088-0a38f200-4b03-11e9-8b15-b6a90f7e6b5d.png)
每个动态表情的所需帧并不相同。
就无法正常工作了。。
我想了好久，发现需要改动UI-Emoji.shader
UV就不能再sharder里操作了
要放到c#代码里操作。。。
您有更好的思路吗？

**Comment by coding2233** [comment]
暂时没有更好的思路，如果有这样的需求，尽量处理为相同数量的图片动画，如果确实不一样，建议可以是使用多个图集

**Comment by ajycode** [comment]
> 希望能把SpriteGraphic脚本下的CellAmount和Speed,两个值集成在SpriteAsset里面
> 这样在多表情的时候用一个图集即可以实现，方便管理，提升性能。
> 我尝试阅读代码，但无奈水平有限，无从下手。
> 如果您能提供下思路，我将不胜感激！谢谢。



> 非常感谢您的帮助，这样的确可以，但是这样有个限制
> 所有表情的CellAmount是相同的。。
> 如果表情切片像这样
> ![1](https://user-images.githubusercontent.com/15153893/54657088-0a38f200-4b03-11e9-8b15-b6a90f7e6b5d.png)
> 每个动态表情的所需帧并不相同。
> 就无法正常工作了。。
> 我想了好久，发现需要改动UI-Emoji.shader
> UV就不能再sharder里操作了
> 要放到c#代码里操作。。。
> 您有更好的思路吗？

可以根据表情图集再生成一张帧数贴图，利用rgba四个通道存储表情帧数，不过这种处理方式最多只能16帧序列图。
再把表情第一帧的uv数据存储下来
这样在shader里通过第一帧的uv采样帧数贴图获取表情帧数，再计算对应帧数相对应的uv偏移，就可以采样到每一帧的数据。
