### ISSUE TITLE
最新的版本大部分问题解决了,还有一个

### ISSUE THREAD

**Issue by SignZun** [coding2233/TextInlineSprite#40]
我聊天界面,把聊天的item删掉了,可是表情还是存在Panel_Sprite里...怎么清除重置啊~

**Comment by coding2233** [comment]
最简单的办法 就是先清除item里文本，再删除item， 这样就会激活Sprite的重新绘制

**Comment by SignZun** [comment]
感谢回复,这样虽然可以,也有点麻烦,大佬能不能加个清空的方法...

**Comment by coding2233** [comment]
这个我可以后续来添加吧，但是最近比较忙，可能没有时间来修改这个，你可以自己先试试

**Comment by SignZun** [comment]
好的把,谢谢了~
